export const EQUIPMENT_TYPES = {
  backhoe:    { label:"Backhoe Loader",      icon:"🟡", brands:["JCB 3DX","JCB 4DX","CAT 424"],              billingUnit:"hour",  avgRate:900,  avgFuel:5,  serviceInterval:250,  lifeHours:12000, category:"earthmoving" },
  excavator:  { label:"Hydraulic Excavator", icon:"🦾", brands:["JCB NXT 215","CAT 320","Tata Hitachi 200"],  billingUnit:"hour",  avgRate:1400, avgFuel:15, serviceInterval:500,  lifeHours:15000, category:"earthmoving" },
  miniexcav:  { label:"Mini Excavator",      icon:"🔶", brands:["JCB 30Plus","CAT 308","Komatsu PC35"],        billingUnit:"hour",  avgRate:600,  avgFuel:4,  serviceInterval:250,  lifeHours:10000, category:"earthmoving" },
  roller:     { label:"Vibratory Roller",    icon:"🔵", brands:["JCB VM115","HAMM HD90","Dynapac CA250"],      billingUnit:"hour",  avgRate:700,  avgFuel:8,  serviceInterval:300,  lifeHours:12000, category:"compaction"  },
  crane:      { label:"Hydraulic Crane",     icon:"🏗️", brands:["SANY 50T","Escorts 30T","Tadano"],            billingUnit:"hour",  avgRate:3500, avgFuel:22, serviceInterval:200,  lifeHours:20000, category:"lifting"     },
  telehandler:{ label:"Telehandler",         icon:"🔧", brands:["JCB 540-170","Manitou MT 625"],               billingUnit:"hour",  avgRate:1100, avgFuel:7,  serviceInterval:300,  lifeHours:12000, category:"handling"    },
  grader:     { label:"Motor Grader",        icon:"⚙️", brands:["JCB 140G","CAT 140","Mahindra"],              billingUnit:"hour",  avgRate:1600, avgFuel:18, serviceInterval:250,  lifeHours:15000, category:"earthmoving" },
  concrete:   { label:"Concrete Mixer",      icon:"🔘", brands:["Ajax Fiori","Schwing Stetter"],               billingUnit:"m3",    avgRate:450,  avgFuel:6,  serviceInterval:500,  lifeHours:8000,  category:"concrete"    },
  transit:    { label:"Transit Mixer",       icon:"🔵", brands:["BharatBenz TM","Tata 1616"],                  billingUnit:"trip",  avgRate:2800, avgFuel:20, serviceInterval:500,  lifeHours:null,  category:"concrete"    },
};