export const VEHICLE_SCHEMA = [
  { id:"tripper", label:"Tripper", icon:"🚛", desc:"Tipping body for bulk material (sand, gravel, coal)", color:"#F59E0B",
    subtypes:[{ id:"tripper_live", label:"Live Axle", wheels:["12 Wheelers","14 Wheelers","16 Wheelers"], capacity:"10–20T" },{ id:"tripper_lift", label:"Lift Axle", wheels:["14 Wheelers","16 Wheelers"], capacity:"15–25T" }],
    specs:{ make:"Tata / Ashok Leyland / BharatBenz", fuelEconomy:"4–5 km/l", avgSpeed:"55–65 kmph" } },
  { id:"openbody", label:"Open Body", icon:"🚚", desc:"Flatbed open carrier for general goods, machinery", color:"#3B82F6",
    subtypes:[{ id:"openbody_std", label:"Standard", wheels:["12 Wheelers","14 Wheelers","16 Wheelers"], capacity:"10–24T" },{ id:"openbody_liftaxle", label:"Lift Axle", wheels:["14 Wheelers","16 Wheelers"], capacity:"18–28T" }],
    specs:{ make:"Tata / EICHER / Mahindra", fuelEconomy:"5–7 km/l", avgSpeed:"60 kmph" } },
  { id:"trailer", label:"Trailer", icon:"🚜", desc:"Long-haul semi-trailer for heavy/oversized loads", color:"#8B5CF6",
    subtypes:[{ id:"trailer_single", label:"Single Trailer", wheels:["2 Axle","3 Axle"], capacity:"20–30T" },{ id:"trailer_double", label:"Double Trailer", wheels:["4 Axle","5 Axle"], capacity:"30–45T" }],
    specs:{ make:"Tata Prima / Volvo / Scania", fuelEconomy:"3–4 km/l", avgSpeed:"55 kmph" } },
  { id:"flatbed", label:"Flatbed", icon:"🛻", desc:"Low-deck flatbed for steel coils, pipes, heavy cargo", color:"#10B981",
    subtypes:[{ id:"flatbed_std", label:"Standard", wheels:["12 Wheelers","14 Wheelers","16 Wheelers"], capacity:"15–30T" },{ id:"flatbed_lowbed", label:"Low Bed", wheels:["6 Axle","8 Axle"], capacity:"30–80T" }],
    specs:{ make:"Tata / KAMA / BharatBenz", fuelEconomy:"4–5 km/l", avgSpeed:"55 kmph" } },
  { id:"container", label:"Container", icon:"📦", desc:"Enclosed container for finished goods, FMCG", color:"#F97316",
    subtypes:[{ id:"container_20ft", label:"20 FT", wheels:["6 Wheeler","10 Wheeler"], capacity:"15–18T" },{ id:"container_32ft", label:"32 FT", wheels:["12 Wheeler","14 Wheeler"], capacity:"20–25T" },{ id:"container_40ft", label:"40 FT HQ", wheels:["16 Wheeler","18 Wheeler"], capacity:"25–30T" }],
    specs:{ make:"Tata / VECV / MAN", fuelEconomy:"6–8 km/l", avgSpeed:"65 kmph" } },
  { id:"lcv", label:"LCV / SCV", icon:"🚐", desc:"Light/small commercial vehicle for last-mile delivery", color:"#94A3B8",
    subtypes:[{ id:"lcv_mini", label:"Mini Truck", wheels:["4 Wheeler"], capacity:"1–2T" },{ id:"lcv_pickup", label:"Pickup", wheels:["4 Wheeler"], capacity:"0.5–1T" }],
    specs:{ make:"Tata Ace / Mahindra Jeeto / Force", fuelEconomy:"12–18 km/l", avgSpeed:"60 kmph" } },
];
